#!/usr/bin/env python3
"""
Daily portion sender for the RLCF Bible study plan.
------------------------------------------------------
Run once per day, Monday through Saturday. Finds the most recent
week-*.json file generated by generate_study_plan.py, figures out which
day of the week it is, and emails just that day's portion.

Sundays are skipped on purpose — that's service day, and it's also when
generate_study_plan.py runs to build the upcoming week's plan.

Environment variables required (email delivery):
  SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, EMAIL_TO, EMAIL_FROM
"""

import os
import sys
import json
import glob
import smtplib
from datetime import datetime
from email.mime.text import MIMEText

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output")

DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]


def get_latest_week_file():
    """Find the most recently generated week-*.json file."""
    pattern = os.path.join(OUTPUT_DIR, "week-*.json")
    matches = sorted(glob.glob(pattern), reverse=True)
    if not matches:
        raise RuntimeError("No week-*.json plan found in output/. "
                            "Has generate_study_plan.py run yet this week?")
    return matches[0]


def get_todays_entry(week_data):
    """Pick out today's day-block from the week's plan. Returns None on Sunday."""
    today_name = datetime.now().strftime("%A")
    if today_name not in DAYS:
        return None, today_name

    for entry in week_data["days"]:
        if entry["day"] == today_name:
            return entry, today_name

    return None, today_name


def format_email_body(week_data, entry, today_name):
    lines = [
        f"{today_name}'s Bible Study",
        "=" * (len(today_name) + 15),
        "",
        f"This week's memory verse: {week_data['memory_verse']}",
        f"From Sunday's message: {week_data['sermon_title']}",
        "",
        f"FOCUS: {entry['focus']}",
        "",
        f"READ: {entry['passage']}",
        "",
        f"REFLECT ON THE MESSAGE: {entry['message_reflection']}",
        "",
        f"TIES TO THE MEMORY VERSE: {entry['related_scripture']}",
        "",
        f"REFLECT ON THE VERSE: {entry['verse_reflection']}",
    ]
    return "\n".join(lines)


def send_email(subject, body):
    required = ["SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASS", "EMAIL_TO", "EMAIL_FROM"]
    if not all(os.environ.get(v) for v in required):
        print("SMTP env vars not fully set — cannot send email. "
              "Printing today's portion instead:\n")
        print(body)
        return

    msg = MIMEText(body, "plain", "utf-8")
    msg["Subject"] = subject
    msg["From"] = os.environ["EMAIL_FROM"]
    msg["To"] = os.environ["EMAIL_TO"]

    with smtplib.SMTP(os.environ["SMTP_HOST"], int(os.environ["SMTP_PORT"])) as server:
        server.starttls()
        server.login(os.environ["SMTP_USER"], os.environ["SMTP_PASS"])
        server.sendmail(os.environ["EMAIL_FROM"], [os.environ["EMAIL_TO"]], msg.as_string())

    print(f"Emailed {subject} to {os.environ['EMAIL_TO']}")


def main():
    week_file = get_latest_week_file()
    with open(week_file, "r", encoding="utf-8") as f:
        week_data = json.load(f)

    entry, today_name = get_todays_entry(week_data)

    if entry is None:
        print(f"Today is {today_name} — no portion to send "
              f"(Sunday is service day / plan-generation day).")
        return

    body = format_email_body(week_data, entry, today_name)
    subject = f"Bible Study — {today_name}: {entry['focus']}"
    send_email(subject, body)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
