#!/usr/bin/env python3
"""
Daily portion sender for the RLCF Bible study plan.
------------------------------------------------------
Run once per day, Monday through Saturday. Finds the most recent
week-*.json file generated by generate_study_plan.py, figures out which
day of the week it is, and delivers just that day's portion via
responsive HTML email (with plain-text fallback) and Slack Block Kit.

Sundays are skipped on purpose — that's service day, and it's also when
generate_study_plan.py runs to build the upcoming week's plan.

Flags:
  --preview      Generate output/preview_today.html and open in web browser
  --day DAY      Override day of week to send/preview (e.g. Monday, Tuesday)
  --dry-run      Print output without actually sending email or posting to Slack

Environment variables required (email delivery):
  SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, EMAIL_TO, EMAIL_FROM

Optional (also posts to Slack alongside the email):
  SLACK_WEBHOOK_URL
"""

import os
import sys
import json
import glob
import smtplib
import argparse
import webbrowser
import urllib.parse
from datetime import datetime, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import requests

if sys.stdout and hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output")
DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
APP_URL = "https://davelane26.github.io/devotional-companion/"


def load_dotenv(filepath=".env"):
    """Optionally load environment variables from a local .env file."""
    target = filepath if os.path.isabs(filepath) else os.path.join(os.path.dirname(__file__), filepath)
    if not os.path.exists(target):
        return
    try:
        with open(target, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, v = line.split("=", 1)
                k = k.strip()
                v = v.strip().strip("'\"")
                if k and k not in os.environ:
                    os.environ[k] = v
    except Exception as e:
        print(f"Warning: could not read {target}: {e}")


load_dotenv()


def bible_gateway_url(ref, version=None):
    """Generate a direct BibleGateway passage link."""
    v = version or os.environ.get("BIBLE_TRANSLATION", "NASB1995")
    clean_ref = ref.strip()
    encoded = urllib.parse.quote_plus(clean_ref)
    return f"https://www.biblegateway.com/passage/?search={encoded}&version={v}"


def get_latest_week_file():
    """Find the most recently generated week-*.json file."""
    pattern = os.path.join(OUTPUT_DIR, "week-*.json")
    matches = sorted(glob.glob(pattern), reverse=True)
    if not matches:
        raise RuntimeError("No week-*.json plan found in output/. "
                           "Has generate_study_plan.py run yet this week?")
    return matches[0]


def get_entry_for_day(week_data, target_day=None):
    """Pick out a specific day's block from the week's plan. Returns (entry, day_name)."""
    day_name = target_day or datetime.now().strftime("%A")
    if day_name not in DAYS:
        return None, day_name

    for entry in week_data.get("days", []):
        if entry.get("day") == day_name:
            return entry, day_name

    return None, day_name


def get_today_book_chapter(target_date_str=None):
    """Fetch today's Book Study chapter from book-schedule.json (graceful fallback)."""
    try:
        url = "https://davelane26.github.io/book-study-plan/output/book-schedule.json"
        resp = requests.get(url, timeout=8)
        if resp.status_code == 200:
            data = resp.json()
            query_date = target_date_str or datetime.now().strftime("%Y-%m-%d")
            item = data.get("schedule", {}).get(query_date)
            if item and item.get("chapters"):
                ch = item["chapters"][0]
                return {
                    "number": ch.get("number"),
                    "title": ch.get("title"),
                    "author": data.get("book_author", "Zac Poonen"),
                    "book_title": data.get("book_title", "Basic Christian Teachings"),
                }
    except Exception as e:
        print(f"Note: Could not fetch book study schedule: {e}")
    return None


def format_email_body(week_data, entry, today_name, book_chapter=None):
    """Plain-text email body (and fallback for non-HTML email clients)."""
    lines = [
        f"{today_name}'s Bible Study",
        "=" * (len(today_name) + 15),
        "",
        f"📱 Devotional Companion App: {APP_URL}",
        "",
        f"This week's memory verse: {week_data.get('memory_verse', '')}",
        f"From Sunday's message: {week_data.get('sermon_title', '')}",
        f"Sermon Link: {week_data.get('sermon_url', '')}",
        "",
        f"FOCUS: {entry.get('focus', '')}",
        "",
        f"READ: {'; '.join(entry.get('passages', []))}",
        "",
        f"MESSAGE RECAP: {entry.get('message_recap', '')}",
        "",
        f"QUOTE FROM THE MESSAGE: \"{entry.get('message_quote', '')}\"",
    ]

    rel = entry.get("related_scripture")
    if rel:
        lines.extend([
            "",
            f"TIES TO THE MEMORY VERSE: {rel}",
        ])

    if book_chapter:
        lines.extend([
            "",
            "--------------------------------------------------",
            f"📚 TODAY'S COMPANION BOOK STUDY: Chapter {book_chapter['number']}: {book_chapter['title']}",
            f"From '{book_chapter['book_title']}' by {book_chapter['author']}",
            f"Listen with follow-along audio in the app: {APP_URL}",
            "--------------------------------------------------",
        ])

    prayer = entry.get("daily_prayer")
    if prayer:
        lines.extend([
            "",
            f"TODAY'S PRAYER: {prayer}",
        ])

    lines.extend([
        "",
        "Open today's full study with Zac Poonen follow-along audio & reflection notes:",
        f"{APP_URL}",
    ])

    return "\n".join(lines)


def format_email_html(week_data, entry, today_name, book_chapter=None, translation=None):
    """Generate responsive, beautifully styled HTML email with clickable links."""
    passages_html = []
    for p in entry.get("passages", []):
        url = bible_gateway_url(p, version=translation)
        passages_html.append(
            f'<a href="{url}" target="_blank" style="display: inline-block; background-color: #eff6ff; color: #1d4ed8; text-decoration: none; padding: 7px 14px; border-radius: 6px; font-weight: 600; font-size: 13px; margin: 3px 4px 3px 0; border: 1px solid #bfdbfe;">📖 {p}</a>'
        )
    passages_markup = "".join(passages_html) if passages_html else "<em>No passages listed</em>"

    rel = entry.get("related_scripture", "")
    rel_url = bible_gateway_url(rel, version=translation) if rel else ""
    rel_markup = f'<a href="{rel_url}" target="_blank" style="display: inline-block; background-color: #f5f3ff; color: #6d28d9; text-decoration: none; padding: 7px 14px; border-radius: 6px; font-weight: 600; font-size: 13px; border: 1px solid #ddd6fe;">🔗 {rel}</a>' if rel else ""

    book_study_section = ""
    if book_chapter:
        book_study_section = f"""
        <div style="background-color: #eef2ff; border: 1px solid #c7d2fe; border-left: 4px solid #6366f1; border-radius: 8px; padding: 18px 20px; margin-bottom: 24px;">
          <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #4338ca; margin-bottom: 6px;">
            📚 Today's Companion Book Study
          </div>
          <div style="font-size: 16px; font-weight: 700; color: #1e1b4b; margin-bottom: 4px;">
            Chapter {book_chapter['number']}: {book_chapter['title']}
          </div>
          <div style="font-size: 13px; color: #4338ca; margin-bottom: 14px;">
            From <em>{book_chapter['book_title']}</em> by {book_chapter['author']}
          </div>
          <a href="{APP_URL}" target="_blank" style="display: inline-block; background-color: #4f46e5; color: #ffffff; text-decoration: none; padding: 8px 16px; border-radius: 6px; font-weight: 600; font-size: 12px; box-shadow: 0 1px 2px rgba(0,0,0,0.05);">
            🎧 Listen with Follow-Along Audio in App &rarr;
          </a>
        </div>
        """

    prayer = entry.get("daily_prayer", "")
    prayer_section = ""
    if prayer:
        prayer_section = f"""
        <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-left: 4px solid #16a34a; border-radius: 8px; padding: 16px 18px; margin-top: 20px;">
          <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #15803d; margin-bottom: 8px;">
            🙏 Today's Closing Prayer
          </div>
          <div style="font-style: italic; color: #166534; line-height: 1.6; font-size: 14px;">
            "{prayer}"
          </div>
        </div>
        """

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{today_name}'s Bible Study</title>
</head>
<body style="margin: 0; padding: 24px 12px; background-color: #f1f5f9; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #334155; line-height: 1.5;">
  <div style="max-width: 620px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.06), 0 2px 4px -2px rgba(0, 0, 0, 0.06); border: 1px solid #e2e8f0;">
    
    <!-- Header Banner -->
    <div style="background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%); padding: 26px 30px; color: #ffffff;">
      <div style="font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #94a3b8; margin-bottom: 8px;">
        RLCF Daily Bible Study &bull; {today_name.upper()}
      </div>
      <h1 style="margin: 0 0 10px 0; font-size: 22px; line-height: 1.35; font-weight: 700; color: #f8fafc;">
        {entry.get('focus', 'Daily Study')}
      </h1>
      <div style="font-size: 13px; color: #cbd5e1; line-height: 1.4; margin-bottom: 14px;">
        From Sunday's Message: <a href="{week_data.get('sermon_url', '#')}" target="_blank" style="color: #60a5fa; text-decoration: none; font-weight: 500;">{week_data.get('sermon_title', '')} &rarr;</a>
      </div>

      <!-- App Deep Link Button -->
      <div>
        <a href="{APP_URL}" target="_blank" style="display: inline-block; background-color: #3b82f6; color: #ffffff; text-decoration: none; padding: 10px 18px; border-radius: 8px; font-weight: 700; font-size: 13px; box-shadow: 0 2px 4px rgba(0,0,0,0.15);">
          📱 Open in Devotional Companion App &rarr;
        </a>
      </div>
    </div>

    <!-- Main Content Container -->
    <div style="padding: 26px 30px;">
      
      <!-- Memory Verse Card -->
      <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 14px 18px; margin-bottom: 22px;">
        <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #64748b; margin-bottom: 6px;">
          Weekly Memory Verse
        </div>
        <div style="font-size: 14px; font-weight: 600; color: #1e293b; line-height: 1.5; font-family: Georgia, serif;">
          {week_data.get('memory_verse', '')}
        </div>
      </div>

      <!-- Readings Section -->
      <div style="margin-bottom: 22px;">
        <div style="font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: #475569; margin-bottom: 8px;">
          Today's Scripture Passage(s)
        </div>
        <div>
          {passages_markup}
        </div>
      </div>

      <!-- Sermon Recap Card -->
      <div style="margin-bottom: 22px;">
        <div style="font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: #475569; margin-bottom: 6px;">
          Message Recap
        </div>
        <p style="margin: 0; font-size: 14px; line-height: 1.6; color: #334155;">
          {entry.get('message_recap', '')}
        </p>
      </div>

      <!-- Sermon Quote Blockquote -->
      <div style="margin-bottom: 22px; background-color: #f8fafc; border-left: 4px solid #3b82f6; border-radius: 4px; padding: 14px 18px;">
        <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: #2563eb; margin-bottom: 6px;">
          Quote from the Message
        </div>
        <div style="font-family: Georgia, serif; font-style: italic; font-size: 14px; color: #1e293b; line-height: 1.6;">
          "{entry.get('message_quote', '')}"
        </div>
      </div>

      <!-- Ties to the Memory Verse (if present) -->
      {"<div style='margin-bottom: 22px;'><div style='font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: #475569; margin-bottom: 6px;'>Ties to the Memory Verse</div><div>" + rel_markup + "</div></div>" if rel else ""}

      <!-- Book Study Section -->
      {book_study_section}

      {prayer_section}

    </div>

    <!-- Footer -->
    <div style="background-color: #f8fafc; border-top: 1px solid #e2e8f0; padding: 20px 30px; text-align: center; font-size: 12px; color: #64748b; line-height: 1.6;">
      <div style="margin-bottom: 8px;">
        <a href="{APP_URL}" target="_blank" style="color: #2563eb; font-weight: 600; text-decoration: none;">
          📱 Open Today's Study in Devotional Companion App
        </a>
      </div>
      <div>
        Redstone Christian Life Fellowship &bull; <a href="{week_data.get('sermon_url', '#')}" target="_blank" style="color: #64748b; text-decoration: underline;">Watch Sunday Sermon</a>
      </div>
    </div>

  </div>
</body>
</html>
"""
    return html


def format_slack_message(week_data, entry, today_name, book_chapter=None, translation=None):
    """Generate Slack Block Kit payload with rich mrkdwn and direct app links."""
    passages_text = " • ".join([f"<{bible_gateway_url(p, version=translation)}|*{p}*>" for p in entry.get("passages", [])])
    rel_scripture = entry.get("related_scripture", "")
    rel_text = f"<{bible_gateway_url(rel_scripture, version=translation)}|*{rel_scripture}*>" if rel_scripture else ""

    mem_verse = week_data.get('memory_verse', '')
    sermon_title = week_data.get('sermon_title', '')
    sermon_url = week_data.get('sermon_url', '#')

    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"📖 {today_name}'s Bible Study: {entry.get('focus', '')[:90]}",
                "emoji": True
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*<https://davelane26.github.io/devotional-companion/|📱 Open in Devotional Companion App (Audio + Follow-Along + Journal) →>*"
            }
        },
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"*Memory Verse:* {mem_verse}\n*Sermon:* <{sermon_url}|{sermon_title}>"
                }
            ]
        },
        {"type": "divider"},
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Today's Scripture Reading:*\n{passages_text}"
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Message Recap:*\n{entry.get('message_recap', '')}"
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Quote from the Message:*\n> \"_{entry.get('message_quote', '')}_\""
            }
        },
    ]

    if rel_text:
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Ties to the Memory Verse:*\n{rel_text}"
            }
        })

    if book_chapter:
        b_num = book_chapter['number']
        b_title = book_chapter['title']
        b_book = book_chapter['book_title']
        b_auth = book_chapter['author']
        blocks.append({"type": "divider"})
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*📚 Today's Companion Book Study: Chapter {b_num}: {b_title}*\n_From '{b_book}' by {b_auth}_\n👉 *<https://davelane26.github.io/devotional-companion/|Listen with follow-along audio in the app →>*"
            }
        })

    prayer = entry.get("daily_prayer")
    if prayer:
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Today's Prayer:*\n_{prayer}_"
            }
        })

    fallback_text = (
        f"*{today_name}'s Bible Study: {entry.get('focus', '')}*\n"
        f"App: {APP_URL}\n"
        f"Read: {', '.join(entry.get('passages', []))}\n"
        f"Recap: {entry.get('message_recap', '')}"
    )

    return fallback_text, blocks


def send_slack(text, blocks=None):
    webhook_url = os.environ.get("SLACK_WEBHOOK_URL")
    if not webhook_url:
        print("SLACK_WEBHOOK_URL not set — skipping Slack delivery.")
        return

    payload = {"text": text}
    if blocks:
        payload["blocks"] = blocks

    resp = requests.post(webhook_url, json=payload, timeout=20)
    if resp.status_code != 200:
        raise RuntimeError(f"Slack webhook returned {resp.status_code}: {resp.text}")

    print("Posted today's portion to Slack (Block Kit formatted)")


def send_email(subject, plain_body, html_body=None):
    required = ["SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASS", "EMAIL_TO", "EMAIL_FROM"]
    if not all(os.environ.get(v) for v in required):
        print("SMTP env vars not fully set — cannot send email.")
        return

    if html_body:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = os.environ["EMAIL_FROM"]
        msg["To"] = os.environ["EMAIL_TO"]
        msg.attach(MIMEText(plain_body, "plain", "utf-8"))
        msg.attach(MIMEText(html_body, "html", "utf-8"))
    else:
        msg = MIMEText(plain_body, "plain", "utf-8")
        msg["Subject"] = subject
        msg["From"] = os.environ["EMAIL_FROM"]
        msg["To"] = os.environ["EMAIL_TO"]

    host = os.environ["SMTP_HOST"]
    port = int(os.environ["SMTP_PORT"])
    user = os.environ["SMTP_USER"]
    password = os.environ["SMTP_PASS"]

    print(f"Connecting to SMTP server {host}:{port}...")
    with smtplib.SMTP(host, port, timeout=30) as server:
        server.ehlo()
        if port != 25:
            server.starttls()
            server.ehlo()
        server.login(user, password)
        server.send_message(msg)

    print(f"Email successfully sent to {os.environ['EMAIL_TO']}")


def parse_args():
    parser = argparse.ArgumentParser(description="Deliver or preview today's RLCF Bible study portion.")
    parser.add_argument("--preview", action="store_true", help="Generate HTML preview and open in browser")
    parser.add_argument("--day", type=str, choices=DAYS, help="Override today's day of week (e.g. Monday)")
    parser.add_argument("--translation", type=str, default=os.environ.get("BIBLE_TRANSLATION", "NASB1995"),
                        help="Bible translation for passage links (e.g. NASB1995, NKJV, ESV, NIV, KJV)")
    parser.add_argument("--dry-run", action="store_true", help="Format and print output without sending email or Slack")
    return parser.parse_args()


def main():
    args = parse_args()
    week_file = get_latest_week_file()
    with open(week_file, "r", encoding="utf-8") as f:
        week_data = json.load(f)

    entry, today_name = get_entry_for_day(week_data, target_day=args.day)

    if entry is None:
        print(f"Today is {today_name} — no portion to send "
              f"(Sunday is service day / plan-generation day).")
        return

    # Calculate date for today_name if --day was supplied
    target_date_str = None
    if args.day and week_data.get("week_of"):
        try:
            week_start = datetime.strptime(week_data["week_of"], "%Y-%m-%d")
            day_idx = DAYS.index(args.day)
            target_date_str = (week_start + timedelta(days=day_idx)).strftime("%Y-%m-%d")
        except Exception:
            pass

    book_chapter = get_today_book_chapter(target_date_str=target_date_str)

    plain_body = format_email_body(week_data, entry, today_name, book_chapter)
    html_body = format_email_html(week_data, entry, today_name, book_chapter, translation=args.translation)
    subject = f"Bible Study — {today_name}: {entry.get('focus', '')}"

    # Handle preview flag
    if args.preview:
        preview_path = os.path.join(OUTPUT_DIR, "preview_today.html")
        with open(preview_path, "w", encoding="utf-8") as f:
            f.write(html_body)
        print(f"Generated email preview: {preview_path}")
        webbrowser.open(f"file://{os.path.abspath(preview_path)}")

    if args.dry_run:
        print("\n=== DRY RUN MODE: Plain-Text Email ===")
        print(plain_body)
        print("\n=== DRY RUN MODE: Slack Fallback & Blocks ===")
        slack_text, slack_blocks = format_slack_message(week_data, entry, today_name, book_chapter, translation=args.translation)
        print(slack_text)
        print(f"Slack blocks count: {len(slack_blocks)}")
        print("\n=== DRY RUN MODE: HTML email generated successfully ===")
        return

    if not args.preview:
        send_email(subject, plain_body, html_body)
        slack_text, slack_blocks = format_slack_message(week_data, entry, today_name, book_chapter, translation=args.translation)
        send_slack(slack_text, slack_blocks)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
